<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-01T08:16:31 CEST" name="Suite" finished-at="2025-06-01T08:17:10 CEST" duration-ms="38729">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.loginErrorValidation()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" name="loginErrorValidation" class="tests.ErrorValidationsTest"/>
        <method signature="ErrorValidationsTest.productErrorValidation()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" name="productErrorValidation" class="tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="purchaseOrder">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:tests.SubmitOrderTest@3ad83a66]" name="submitOrder" class="tests.SubmitOrderTest"/>
      </group> <!-- purchaseOrder -->
    </groups>
    <test started-at="2025-06-01T08:16:31 CEST" name="Submit Order Test" finished-at="2025-06-01T08:17:08 CEST" duration-ms="36817">
      <class name="tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.SubmitOrderTest@3ad83a66]" started-at="2025-06-01T08:16:31 CEST" name="launchApplication" finished-at="2025-06-01T08:16:41 CEST" duration-ms="9818" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:tests.SubmitOrderTest@3ad83a66]" started-at="2025-06-01T08:16:41 CEST" name="submitOrder" data-provider="getData" finished-at="2025-06-01T08:16:50 CEST" duration-ms="9029" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{country=India, password=easypw, orderItem=ZARA COAT 3, email=a@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.SubmitOrderTest@3ad83a66]" started-at="2025-06-01T08:16:50 CEST" name="tearDown" finished-at="2025-06-01T08:16:58 CEST" duration-ms="7331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.SubmitOrderTest@3ad83a66]" started-at="2025-06-01T08:16:58 CEST" name="launchApplication" finished-at="2025-06-01T08:17:04 CEST" duration-ms="6007" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:tests.SubmitOrderTest@3ad83a66]" started-at="2025-06-01T08:17:04 CEST" name="submitOrder" data-provider="getData" finished-at="2025-06-01T08:17:07 CEST" duration-ms="3197" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{country=Poland, password=GHcwBkaZZ$fcW6W, orderItem=ADIDAS ORIGINAL, email=thoufeeque.rafique@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.SubmitOrderTest.submitOrder(SubmitOrderTest.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.SubmitOrderTest@3ad83a66]" started-at="2025-06-01T08:17:07 CEST" name="tearDown" finished-at="2025-06-01T08:17:08 CEST" duration-ms="713" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="orderHistoryTest()[pri:0, instance:tests.SubmitOrderTest@3ad83a66]" started-at="2025-06-01T08:17:08 CEST" name="orderHistoryTest" finished-at="2025-06-01T08:17:08 CEST" depends-on-methods="tests.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.SubmitOrderTest.orderHistoryTest() on instance tests.SubmitOrderTest@3ad83a66 depends on not successfully finished methods 
[tests.SubmitOrderTest.submitOrder() on instance tests.SubmitOrderTest@3ad83a66]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.SubmitOrderTest.orderHistoryTest() on instance tests.SubmitOrderTest@3ad83a66 depends on not successfully finished methods 
[tests.SubmitOrderTest.submitOrder() on instance tests.SubmitOrderTest@3ad83a66]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
      </class> <!-- tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2025-06-01T08:16:31 CEST" name="Error Validation Tests" finished-at="2025-06-01T08:17:10 CEST" duration-ms="38729">
      <class name="tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" started-at="2025-06-01T08:16:31 CEST" name="launchApplication" finished-at="2025-06-01T08:16:41 CEST" duration-ms="10338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" started-at="2025-06-01T08:16:41 CEST" name="loginErrorValidation" finished-at="2025-06-01T08:16:43 CEST" duration-ms="1445" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email oir password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email oir password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.ErrorValidationsTest.loginErrorValidation(ErrorValidationsTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" started-at="2025-06-01T08:16:43 CEST" name="tearDown" finished-at="2025-06-01T08:16:44 CEST" duration-ms="757" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" started-at="2025-06-01T08:16:44 CEST" name="launchApplication" finished-at="2025-06-01T08:16:50 CEST" duration-ms="6163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" started-at="2025-06-01T08:16:50 CEST" name="loginErrorValidation" finished-at="2025-06-01T08:16:51 CEST" duration-ms="1422" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email oir password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email oir password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.ErrorValidationsTest.loginErrorValidation(ErrorValidationsTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" started-at="2025-06-01T08:16:52 CEST" name="tearDown" finished-at="2025-06-01T08:16:58 CEST" duration-ms="5672" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" started-at="2025-06-01T08:16:58 CEST" name="launchApplication" finished-at="2025-06-01T08:17:03 CEST" duration-ms="5525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" started-at="2025-06-01T08:17:03 CEST" name="productErrorValidation" finished-at="2025-06-01T08:17:07 CEST" duration-ms="4446" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.ErrorValidationsTest@49b2a47d]" started-at="2025-06-01T08:17:07 CEST" name="tearDown" finished-at="2025-06-01T08:17:10 CEST" duration-ms="2205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.ErrorValidationsTest -->
    </test> <!-- Error Validation Tests -->
  </suite> <!-- Suite -->
</testng-results>
